import type { DemoMotif } from '#database/support/demo/illustration/scenes'

/** What each motif shows, in the words its alternative text uses. */
export const DEMO_MOTIF_ALT: Record<DemoMotif, string> = {
  coffee: 'xícara de café sobre a mesa',
  pasta: 'prato de massa com molho de tomate',
  grill: 'tábua com carne grelhada e batatas',
  homestyle: 'prato feito com arroz, feijão e salada',
  bar: 'chope, caipirinha e petiscos no balcão',
  bakery: 'pães artesanais sobre a tábua',
  sweets: 'bolo, cupcakes e brigadeiros',
  burger: 'hambúrguer, batatas fritas e refrigerante',
  pizza: 'pizza inteira sobre a tábua',
  sushi: 'sushis e hashis sobre a tábua',
  icecream: 'casquinhas de sorvete e picolés',
  deli: 'prateleiras com potes, garrafas e queijos',
  cinema: 'claquete, pipoca e rolo de filme',
  music: 'violão e microfone no palco',
  gallery: 'quadros na parede de uma galeria',
  books: 'pilha de livros e óculos de leitura',
  bowling: 'pinos e bolas de boliche',
  heritage: 'fachada de casarão com colunas',
  park: 'parque com árvores, caminho e banco',
  trail: 'trilha entre araucárias e morros',
  farm: 'celeiro, cerca e plantação',
  lake: 'lago com deque e vara de pesca',
  lookout: 'mirante com vista do pôr do sol',
  yoga: 'tapete de yoga, planta e pedras',
  spa: 'toalhas enroladas, pedras e flores',
  tattoo: 'desenhos de tatuagem e tintas',
  barber: 'espelho, poste de barbearia e tesoura',
  flowers: 'buquê de flores e vasos',
  pet: 'pote de ração, osso e patinhas',
  bike: 'bicicleta na oficina',
  ceramics: 'vasos de cerâmica e torno',
  sewing: 'tecidos, linhas e tesoura',
}
