export const BENEFIT_PRESENTATION_TOKEN_MIN_LENGTH = 45
export const BENEFIT_PRESENTATION_TOKEN_MAX_LENGTH = 512
export const BENEFIT_PRESENTATION_TOKEN_PATTERN = /^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]{43}$/

export const BENEFIT_RECEIPT_CODE_LENGTH = 20
export const BENEFIT_RECEIPT_CODE_PATTERN = /^EXP-[0-9A-F]{16}$/
