import { configApp } from '@adonisjs/eslint-config'

export default [
  ...configApp({
    // database/schema.ts is auto-generated by Lucid ("DO NOT EDIT") and its
    // inline array formatting trips prettier — ignore the generated artifact.
    ignores: [
      'tmp/**',
      'build/**',
      'node_modules/**',
      '.winx/**',
      '.playwright-cli/**',
      '.DS_Store',
      'coverage/**',
      'database/schema.ts',
    ],
  }),
  {
    rules: {
      // Re-habilitar na Fase 5 (UI), quando o frontend for reescrito com Link tipado.
      '@adonisjs/prefer-adonisjs-inertia-link': 'off',
    },
  },
]
