import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { access, readFile } from 'node:fs/promises'
import { test } from 'node:test'
import { fileURLToPath } from 'node:url'

// Source-only gate: no build, Docker, server or database. It pins how the
// installable-site files reach the production image.
const project = fileURLToPath(new URL('../../', import.meta.url))
const read = (path) => readFile(new URL(`../../${path}`, import.meta.url), 'utf8')
const env = { PATH: process.env.PATH, GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null' }

function gitIgnores(path) {
  const result = spawnSync('git', ['-C', project, 'check-ignore', '--quiet', '--', path], { env })
  assert.ok(result.status === 0 || result.status === 1, `git check-ignore failed for ${path}`)
  return result.status === 0
}

test('the checked-in PWA files ship: tracked by Git, kept in the Docker context', async () => {
  const manifest = JSON.parse(await read('public/manifest.webmanifest'))
  const files = [
    'public/manifest.webmanifest',
    'public/offline.html',
    'public/apple-touch-icon.png',
    ...manifest.icons.map((icon) => `public${icon.src}`),
    ...manifest.shortcuts.flatMap((shortcut) => shortcut.icons.map((icon) => `public${icon.src}`)),
    ...manifest.screenshots.map((screenshot) => `public${screenshot.src}`),
  ]

  // The deploy builds the image from a Git snapshot: an ignored file would silently be missing.
  for (const file of files) {
    await access(new URL(`../../${file}`, import.meta.url))
    assert.equal(gitIgnores(file), false, `${file} must not be git-ignored`)
  }

  const dockerRules = (await read('.dockerignore'))
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
  assert.ok(
    dockerRules.every((rule) => !/^(?:\*\*\/)?public\b/.test(rule)),
    '.dockerignore must not drop public/'
  )
})

test('the image builds the service worker instead of taking a local copy', async () => {
  const vite = await read('vite.config.ts')
  const dockerfile = await read('Dockerfile')
  const adonisrc = await read('adonisrc.ts')

  // Generated by the Vite client build into public/, never committed.
  assert.match(vite, /resolve\(root, 'public\/sw\.js'\)/)
  assert.match(vite, /plugins: \[[\s\S]*serviceWorker\(\),[\s\S]*\]/)
  assert.equal(gitIgnores('public/sw.js'), true, 'public/sw.js is generated and must stay ignored')

  // `pnpm build` runs the Vite build hook after the source is copied, then the AdonisJS
  // build copies public/** (the worker included) into build/, which the runtime receives.
  assert.match(adonisrc, /buildStarting: \[\(\) => import\('@adonisjs\/vite\/build_hook'\)\]/)
  assert.match(adonisrc, /pattern: 'public\/\*\*'/)
  const copySource = dockerfile.indexOf('COPY . .')
  const build = dockerfile.indexOf('pnpm build')
  assert.ok(copySource > -1 && build > copySource, 'the build must run on the copied source')
  assert.match(dockerfile, /^COPY --from=build \/app\/build \.\/$/m)
})

test('the proxy leaves the service worker and its headers to the application', async () => {
  const virtualHost = await read('infra/nginx/experimente-plus.conf')

  // A single proxied location: nginx never serves /sw.js from disk or rewrites its caching.
  assert.equal(virtualHost.match(/location\s/g)?.length, 1)
  assert.doesNotMatch(virtualHost, /sw\.js|Service-Worker|expires\s/)
})
