import { BaseSchema } from '@adonisjs/lucid/schema'

/** EP-14: forward-only addition; never rewrites the published benefits schema. */
export default class extends BaseSchema {
  async up() {
    this.schema.createTable('purchases', (t) => {
      t.uuid('id').primary()
      t.integer('tenant_id').notNullable()
      t.integer('edition_id').notNullable()
      t.integer('user_id').notNullable()
      t.string('key_hash', 64).notNullable()
      t.string('request_hash', 64).notNullable()
      t.jsonb('snapshot').notNullable()
      t.integer('amount_cents').notNullable()
      t.string('currency', 3).notNullable()
      t.string('method', 16).notNullable()
      t.string('provider', 32).notNullable()
      t.string('provider_account', 100).notNullable()
      t.string('provider_environment', 16).notNullable()
      t.string('provider_id', 150).nullable()
      t.string('status', 24).notNullable().defaultTo('pending')
      t.integer('access_id').nullable()
      t.text('payment_input').nullable() // encrypted, short-lived tokenized input; never PAN/CVV
      t.jsonb('instructions').nullable()
      t.timestamp('expires_at', { useTz: true }).notNullable()
      t.timestamp('paid_at', { useTz: true }).nullable()
      t.timestamp('checked_at', { useTz: true }).nullable()
      t.integer('refunded_cents').notNullable().defaultTo(0)
      t.string('issue', 80).nullable()
      t.timestamp('created_at', { useTz: true }).notNullable().defaultTo(this.now())
      t.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(this.now())
      t.unique(['id', 'tenant_id'])
      t.unique(['tenant_id', 'user_id', 'key_hash'])
      t.unique(['provider', 'provider_account', 'provider_environment', 'provider_id'])
      t.unique(['access_id'])
      t.foreign(['edition_id', 'tenant_id'])
        .references(['id', 'tenant_id'])
        .inTable('benefit_editions')
        .onDelete('RESTRICT')
      t.foreign(['user_id', 'tenant_id'])
        .references(['user_id', 'tenant_id'])
        .inTable('user_tenants')
        .onDelete('RESTRICT')
      t.foreign(['access_id', 'tenant_id'])
        .references(['id', 'tenant_id'])
        .inTable('benefit_accesses')
        .onDelete('RESTRICT')
      t.check("status IN ('pending','paid','review','failed','cancelled','refunded')")
      t.check("method IN ('pix','card')")
      t.check("amount_cents > 0 AND currency = 'BRL' AND refunded_cents BETWEEN 0 AND amount_cents")
      t.index(['tenant_id', 'user_id', 'created_at'])
    })
    this.schema.createTable('purchase_refunds', (t) => {
      t.uuid('id').primary()
      t.uuid('purchase_id').notNullable()
      t.integer('tenant_id').notNullable()
      t.string('key_hash', 64).notNullable()
      t.string('request_hash', 64).notNullable()
      t.integer('amount_cents').notNullable()
      t.string('status', 24).notNullable()
      t.text('reason').notNullable()
      t.integer('requested_by').nullable().references('id').inTable('users').onDelete('SET NULL')
      t.integer('decided_by').nullable().references('id').inTable('users').onDelete('SET NULL')
      t.text('decision_reason').nullable()
      t.string('provider_id', 150).nullable()
      t.integer('baseline_refunded_cents').notNullable().defaultTo(0)
      t.timestamp('created_at', { useTz: true }).notNullable().defaultTo(this.now())
      t.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(this.now())
      t.foreign(['purchase_id', 'tenant_id'])
        .references(['id', 'tenant_id'])
        .inTable('purchases')
        .onDelete('RESTRICT')
      t.unique(['purchase_id', 'key_hash'])
      t.check('amount_cents > 0')
      t.check("status IN ('review','approved','processing','succeeded','failed','rejected')")
    })
    this.schema.createTable('purchase_financial_holds', (t) => {
      t.uuid('id').primary()
      t.uuid('purchase_id').notNullable()
      t.integer('tenant_id').notNullable()
      t.integer('access_id').nullable()
      t.string('reason', 180).notNullable()
      t.timestamp('created_at', { useTz: true }).notNullable().defaultTo(this.now())
      t.timestamp('released_at', { useTz: true }).nullable()
      t.foreign(['purchase_id', 'tenant_id'])
        .references(['id', 'tenant_id'])
        .inTable('purchases')
        .onDelete('RESTRICT')
      t.foreign(['access_id', 'tenant_id'])
        .references(['id', 'tenant_id'])
        .inTable('benefit_accesses')
        .onDelete('RESTRICT')
      t.unique(['purchase_id', 'reason'])
      t.index(['tenant_id', 'access_id', 'released_at'])
    })
    this.schema.createTable('purchase_commands', (t) => {
      t.uuid('id').primary()
      t.uuid('purchase_id').notNullable().references('id').inTable('purchases').onDelete('RESTRICT')
      t.string('kind', 16).notNullable()
      t.uuid('refund_id')
        .nullable()
        .references('id')
        .inTable('purchase_refunds')
        .onDelete('RESTRICT')
      t.string('dedupe_key', 180).notNullable().unique()
      t.string('status', 16).notNullable().defaultTo('pending')
      t.integer('attempts').notNullable().defaultTo(0)
      t.timestamp('available_at', { useTz: true }).notNullable().defaultTo(this.now())
      t.timestamp('lease_until', { useTz: true }).nullable()
      t.uuid('lease_token').nullable()
      t.string('last_error', 80).nullable()
      t.timestamp('created_at', { useTz: true }).notNullable().defaultTo(this.now())
      t.check("kind IN ('create','reconcile','refund','cancel')")
      t.check("status IN ('pending','processing','done','review')")
      t.index(['status', 'available_at'])
    })
    this.schema.createTable('purchase_webhooks', (t) => {
      t.uuid('id').primary()
      t.string('provider', 32).notNullable()
      t.string('account', 100).notNullable()
      t.string('environment', 16).notNullable()
      t.string('event_key', 64).notNullable()
      t.string('resource_id', 150).notNullable()
      t.uuid('purchase_id').nullable().references('id').inTable('purchases').onDelete('RESTRICT')
      t.timestamp('received_at', { useTz: true }).notNullable().defaultTo(this.now())
      t.timestamp('processed_at', { useTz: true }).nullable()
      t.unique(['provider', 'account', 'environment', 'event_key'])
    })
    this.schema.createTable('purchase_events', (t) => {
      t.bigIncrements('id')
      t.uuid('purchase_id').notNullable().references('id').inTable('purchases').onDelete('RESTRICT')
      t.integer('tenant_id').notNullable()
      t.integer('actor_id').nullable().references('id').inTable('users').onDelete('SET NULL')
      t.string('action', 80).notNullable()
      t.jsonb('data').notNullable()
      t.timestamp('created_at', { useTz: true }).notNullable().defaultTo(this.now())
      t.index(['tenant_id', 'purchase_id', 'created_at'])
    })
    this.schema.createTable('purchase_fake_payments', (t) => {
      t.string('id', 150).primary()
      t.uuid('purchase_id').notNullable().unique()
      t.jsonb('state').notNullable()
    })
    this.defer(async (db) => {
      await db.rawQuery(
        `CREATE UNIQUE INDEX purchases_live_holder_unique ON purchases(tenant_id,edition_id,user_id) WHERE status IN ('pending','paid','review')`
      )
      await db.rawQuery(
        `CREATE UNIQUE INDEX purchase_refunds_processing_unique ON purchase_refunds(purchase_id) WHERE status IN ('review','approved','processing')`
      )
      // Financial evidence is append-only even for accidental application updates.
      await db.rawQuery(
        `CREATE FUNCTION purchase_events_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Purchase audit events are immutable'; END; $$`
      )
      await db.rawQuery(
        `CREATE TRIGGER purchase_events_immutable BEFORE UPDATE OR DELETE ON purchase_events FOR EACH ROW EXECUTE FUNCTION purchase_events_immutable()`
      )
    })
  }
  async down() {
    throw new Error(
      'Published financial history is forward-only; restore code without dropping the ledger'
    )
  }
}
